language: python
python: "3.6"
# command to install dependencies
install: pip install -r requirements.txt
# command to run tests
script: python -m unittest discover
# deploy to pypi
deploy:
 provider: pypi
 user: "benhid"
 password:
   secure: "nVjbo3Dw0mTL6IL7npg9ZuJpoFK6BSIo/dXM8MXO24skGPHhibNl87QLoVyw+aU7GOJRuT51VaPVt+HgEm1i4qLgt517C3NTCoMF0CrOQ9KiqfXYFKxMUGa4PL7sBocNpPLvw5zNRFIJO4b4pmZ7Fl4ZnC+2lZsEBUHw5qJjDpWnbV7RWyQ/OeheDgTvvSsQHFGugep//vT541+APE4qqmMn82e57MAwB6ffgNNGwo5MW0Wen7zpmUmoqdiG3zSbI3n1eIi66EYIEAOCnPwARFmlBpBqmYr+2OZFm7p3IQdYa6QeBmr/Ku2VQFp3lR/nNkmg2D44HVgpGStiVncVZs4EC8BYSGb1/QSNA7JMYx56FDk7SK/EZliPyPwDHYP2xpQU+D+C6Z0PF0QNnBZh3nReZQe6eIeuH6++D/ax32Uks2ay+7xr4y/aCk2jq7fFZTk8CeeliojmZZbLAxIha56uMJ51VCDV5mDaSrTypr0HAVzKaJl9ZDHE5wtgXDJZKUE8rMKmumRNSpEJOV6otTlMgoWYBAz7MuUVrnvm77LBl0no0FCc5Z3s7GYGBaXRVf56veD7boFjUFiij7DM5+qoLRobFgZbcFRJK5gaGyTt1rZ3rSYeAX9AVr/Y9UyZQoyvT0vrmGYZ/rm1b5zMYCbnADvmxuiadqwhPtzSUks="
 on:
   branch: master